; ═══════════════════════════════════════════════
; Generated by RustSlicer
; Profile: Enhanced PLA Profile
; Material: PLA
; Layer height: 0.20mm
; Infill: 20% gyroid
; Perimeters: 3
; ═══════════════════════════════════════════════

; Start G-code
G28 ; Home all axes
G1 Z15.0 F6000 ; Move platform down
G92 E0 ; Reset extruder
G1 F200 E3 ; Extrude a short distance
G92 E0 ; Reset extruder again
M117 Printing... ; Display message

; Initialize printer
M82 ; Absolute extrusion mode
M104 S210 ; Set hotend temperature
M140 S60 ; Set bed temperature
M109 S210 ; Wait for hotend
M190 S60 ; Wait for bed
G92 E0 ; Reset extruder
G90 ; Absolute positioning

; Layer 0 at Z=0.300
G0 Z0.300 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-9.700 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-9.700 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-9.700 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-9.700 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 1 at Z=0.300
G0 Z0.300 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-9.700 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-9.700 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-9.700 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-9.700 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 2 at Z=0.500
G0 Z0.500 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-9.500 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-9.500 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-9.500 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-9.500 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 3 at Z=0.700
G0 Z0.700 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-9.300 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-9.300 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-9.300 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-9.300 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 4 at Z=0.900
G0 Z0.900 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-9.100 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-9.100 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-9.100 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-9.100 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 5 at Z=1.100
G0 Z1.100 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-8.900 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-8.900 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-8.900 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-8.900 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 6 at Z=1.300
G0 Z1.300 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-8.700 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-8.700 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-8.700 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-8.700 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 7 at Z=1.500
G0 Z1.500 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-8.500 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-8.500 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-8.500 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-8.500 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 8 at Z=1.700
G0 Z1.700 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-8.300 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-8.300 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-8.300 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-8.300 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 9 at Z=1.900
G0 Z1.900 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-8.100 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-8.100 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-8.100 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-8.100 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 10 at Z=2.100
G0 Z2.100 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-7.900 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-7.900 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-7.900 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-7.900 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 11 at Z=2.300
G0 Z2.300 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-7.700 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-7.700 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-7.700 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-7.700 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 12 at Z=2.500
G0 Z2.500 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-7.500 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-7.500 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-7.500 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-7.500 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 13 at Z=2.700
G0 Z2.700 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-7.300 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-7.300 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-7.300 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-7.300 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 14 at Z=2.900
G0 Z2.900 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-7.100 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-7.100 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-7.100 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-7.100 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 15 at Z=3.100
G0 Z3.100 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-6.900 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-6.900 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-6.900 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-6.900 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 16 at Z=3.300
G0 Z3.300 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-6.700 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-6.700 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-6.700 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-6.700 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 17 at Z=3.500
G0 Z3.500 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-6.500 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-6.500 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-6.500 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-6.500 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 18 at Z=3.700
G0 Z3.700 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-6.300 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-6.300 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-6.300 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-6.300 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 19 at Z=3.900
G0 Z3.900 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-6.100 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-6.100 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-6.100 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-6.100 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 20 at Z=4.100
G0 Z4.100 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-5.900 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-5.900 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-5.900 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-5.900 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 21 at Z=4.300
G0 Z4.300 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-5.700 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-5.700 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-5.700 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-5.700 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 22 at Z=4.500
G0 Z4.500 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-5.500 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-5.500 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-5.500 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-5.500 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 23 at Z=4.700
G0 Z4.700 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-5.300 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-5.300 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-5.300 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-5.300 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 24 at Z=4.900
G0 Z4.900 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-5.100 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-5.100 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-5.100 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-5.100 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 25 at Z=5.100
G0 Z5.100 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-4.900 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-4.900 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-4.900 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-4.900 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 26 at Z=5.300
G0 Z5.300 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-4.700 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-4.700 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-4.700 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-4.700 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 27 at Z=5.500
G0 Z5.500 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-4.500 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-4.500 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-4.500 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-4.500 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 28 at Z=5.700
G0 Z5.700 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-4.300 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-4.300 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-4.300 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-4.300 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 29 at Z=5.900
G0 Z5.900 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-4.100 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-4.100 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-4.100 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-4.100 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 30 at Z=6.100
G0 Z6.100 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-3.900 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-3.900 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-3.900 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-3.900 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 31 at Z=6.300
G0 Z6.300 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-3.700 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-3.700 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-3.700 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-3.700 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 32 at Z=6.500
G0 Z6.500 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-3.500 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-3.500 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-3.500 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-3.500 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 33 at Z=6.700
G0 Z6.700 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-3.300 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-3.300 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-3.300 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-3.300 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 34 at Z=6.900
G0 Z6.900 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-3.100 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-3.100 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-3.100 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-3.100 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 35 at Z=7.100
G0 Z7.100 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-2.900 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-2.900 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-2.900 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-2.900 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 36 at Z=7.300
G0 Z7.300 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-2.700 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-2.700 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-2.700 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-2.700 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 37 at Z=7.500
G0 Z7.500 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-2.500 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-2.500 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-2.500 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-2.500 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 38 at Z=7.700
G0 Z7.700 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-2.300 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-2.300 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-2.300 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-2.300 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 39 at Z=7.900
G0 Z7.900 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-2.100 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-2.100 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-2.100 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-2.100 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 40 at Z=8.100
G0 Z8.100 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-1.900 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-1.900 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-1.900 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-1.900 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 41 at Z=8.300
G0 Z8.300 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-1.700 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-1.700 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-1.700 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-1.700 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 42 at Z=8.500
G0 Z8.500 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-1.500 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-1.500 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-1.500 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-1.500 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 43 at Z=8.700
G0 Z8.700 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-1.300 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-1.300 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-1.300 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-1.300 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 44 at Z=8.900
G0 Z8.900 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-1.100 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-1.100 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-1.100 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-1.100 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 45 at Z=9.100
G0 Z9.100 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-0.900 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-0.900 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-0.900 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-0.900 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 46 at Z=9.300
G0 Z9.300 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-0.700 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-0.700 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-0.700 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-0.700 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 47 at Z=9.500
G0 Z9.500 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-0.500 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-0.500 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-0.500 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-0.500 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 48 at Z=9.700
G0 Z9.700 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-0.300 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-0.300 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-0.300 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-0.300 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 49 at Z=9.900
G0 Z9.900 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X-0.100 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y-0.100 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X-0.100 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y-0.100 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 50 at Z=10.100
G0 Z10.100 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X0.100 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y0.100 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X0.100 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y0.100 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 51 at Z=10.300
G0 Z10.300 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X0.300 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y0.300 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X0.300 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y0.300 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 52 at Z=10.500
G0 Z10.500 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X0.500 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y0.500 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X0.500 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y0.500 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 53 at Z=10.700
G0 Z10.700 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X0.700 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y0.700 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X0.700 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y0.700 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 54 at Z=10.900
G0 Z10.900 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X0.900 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y0.900 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X0.900 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y0.900 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 55 at Z=11.100
G0 Z11.100 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X1.100 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y1.100 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X1.100 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y1.100 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 56 at Z=11.300
G0 Z11.300 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X1.300 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y1.300 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X1.300 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y1.300 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 57 at Z=11.500
G0 Z11.500 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X1.500 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y1.500 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X1.500 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y1.500 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 58 at Z=11.700
G0 Z11.700 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X1.700 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y1.700 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X1.700 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y1.700 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 59 at Z=11.900
G0 Z11.900 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X1.900 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y1.900 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X1.900 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y1.900 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 60 at Z=12.100
G0 Z12.100 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X2.100 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y2.100 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X2.100 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y2.100 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 61 at Z=12.300
G0 Z12.300 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X2.300 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y2.300 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X2.300 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y2.300 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 62 at Z=12.500
G0 Z12.500 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X2.500 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y2.500 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X2.500 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y2.500 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 63 at Z=12.700
G0 Z12.700 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X2.700 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y2.700 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X2.700 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y2.700 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 64 at Z=12.900
G0 Z12.900 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X2.900 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y2.900 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X2.900 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y2.900 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 65 at Z=13.100
G0 Z13.100 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X3.100 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y3.100 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X3.100 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y3.100 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 66 at Z=13.300
G0 Z13.300 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X3.300 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y3.300 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X3.300 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y3.300 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 67 at Z=13.500
G0 Z13.500 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X3.500 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y3.500 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X3.500 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y3.500 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 68 at Z=13.700
G0 Z13.700 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X3.700 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y3.700 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X3.700 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y3.700 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 69 at Z=13.900
G0 Z13.900 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X3.900 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y3.900 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X3.900 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y3.900 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 70 at Z=14.100
G0 Z14.100 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X4.100 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y4.100 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X4.100 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y4.100 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 71 at Z=14.300
G0 Z14.300 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X4.300 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y4.300 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X4.300 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y4.300 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 72 at Z=14.500
G0 Z14.500 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X4.500 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y4.500 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X4.500 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y4.500 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 73 at Z=14.700
G0 Z14.700 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X4.700 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y4.700 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X4.700 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y4.700 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 74 at Z=14.900
G0 Z14.900 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X4.900 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y4.900 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X4.900 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y4.900 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 75 at Z=15.100
G0 Z15.100 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X5.100 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y5.100 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X5.100 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y5.100 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 76 at Z=15.300
G0 Z15.300 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X5.300 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y5.300 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X5.300 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y5.300 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 77 at Z=15.500
G0 Z15.500 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X5.500 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y5.500 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X5.500 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y5.500 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 78 at Z=15.700
G0 Z15.700 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X5.700 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y5.700 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X5.700 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y5.700 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 79 at Z=15.900
G0 Z15.900 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X5.900 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y5.900 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X5.900 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y5.900 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 80 at Z=16.100
G0 Z16.100 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X6.100 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y6.100 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X6.100 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y6.100 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 81 at Z=16.300
G0 Z16.300 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X6.300 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y6.300 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X6.300 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y6.300 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 82 at Z=16.500
G0 Z16.500 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X6.500 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y6.500 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X6.500 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y6.500 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 83 at Z=16.700
G0 Z16.700 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X6.700 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y6.700 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X6.700 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y6.700 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 84 at Z=16.900
G0 Z16.900 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X6.900 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y6.900 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X6.900 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y6.900 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 85 at Z=17.100
G0 Z17.100 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X7.100 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y7.100 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X7.100 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y7.100 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 86 at Z=17.300
G0 Z17.300 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X7.300 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y7.300 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X7.300 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y7.300 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 87 at Z=17.500
G0 Z17.500 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X7.500 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y7.500 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X7.500 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y7.500 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 88 at Z=17.700
G0 Z17.700 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X7.700 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y7.700 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X7.700 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y7.700 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 89 at Z=17.900
G0 Z17.900 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X7.900 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y7.900 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X7.900 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y7.900 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 90 at Z=18.100
G0 Z18.100 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X8.100 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y8.100 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X8.100 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y8.100 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 91 at Z=18.300
G0 Z18.300 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X8.300 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y8.300 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X8.300 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y8.300 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 92 at Z=18.500
G0 Z18.500 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X8.500 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y8.500 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X8.500 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y8.500 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 93 at Z=18.700
G0 Z18.700 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X8.700 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y8.700 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X8.700 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y8.700 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 94 at Z=18.900
G0 Z18.900 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X8.900 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y8.900 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X8.900 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y8.900 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 95 at Z=19.100
G0 Z19.100 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X9.100 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y9.100 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X9.100 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y9.100 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 96 at Z=19.300
G0 Z19.300 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X9.300 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y9.300 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X9.300 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y9.300 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 97 at Z=19.500
G0 Z19.500 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X9.500 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y9.500 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X9.500 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y9.500 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 98 at Z=19.700
G0 Z19.700 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X9.700 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y9.700 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X9.700 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y9.700 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter
; Layer 99 at Z=19.900
G0 Z19.900 ; Move to layer height
; Island 0
G0 X10.000 Y-10.000 ; Move to perimeter start
G1 X9.900 Y-10.000 ; Perimeter
G1 X-10.000 Y-10.000 ; Perimeter
G1 X-10.000 Y9.900 ; Perimeter
G1 X-10.000 Y10.000 ; Perimeter
G1 X9.900 Y10.000 ; Perimeter
G1 X10.000 Y10.000 ; Perimeter
G1 X10.000 Y9.900 ; Perimeter
G1 X10.000 Y-10.000 ; Perimeter
G1 X10.000 Y-10.000 ; Close perimeter

; ═══════════════════════════════════════════════
; End of print
; ═══════════════════════════════════════════════
; End G-code
M104 S0 ; Turn off hotend
M140 S0 ; Turn off bed
G91 ; Relative positioning
G1 E-2 F2700 ; Retract filament
G1 Z10 ; Raise Z
G90 ; Absolute positioning
G28 X Y ; Home X and Y
M84 ; Disable motors
M117 Print complete! ; Display message

