use crate::slicer::Layer;
use crate::config::SlicerConfig;
use crate::error::{SlicerError, Result};
use std::fs::File;
use std::io::{BufWriter, Write};
use std::path::Path;

pub struct GCodeGenerator {
    config: SlicerConfig,
}

impl GCodeGenerator {
    pub fn new(config: SlicerConfig) -> Self {
        GCodeGenerator { config }
    }

    pub fn generate<P: AsRef<Path>>(&self, layers: &[Layer], output_path: P) -> Result<()> {
        let file = File::create(output_path)
            .map_err(|e| SlicerError::GCodeError(format!("Failed to create output file: {}", e)))?;
        
        let mut writer = BufWriter::new(file);

        // Write header
        self.write_header(&mut writer)?;

        // Write layers
        for (i, layer) in layers.iter().enumerate() {
            self.write_layer(&mut writer, layer, i)?;
        }

        // Write footer
        self.write_footer(&mut writer)?;

        writer.flush()
            .map_err(|e| SlicerError::GCodeError(format!("Failed to flush output: {}", e)))?;

        Ok(())
    }

    fn write_header(&self, writer: &mut BufWriter<File>) -> Result<()> {
        writeln!(writer, "; Generated by RustSlicer")?;
        writeln!(writer, "; Layer height: {} mm", self.config.layer_height)?;
        writeln!(writer, "; Infill: {}%", self.config.infill_percentage)?;
        writeln!(writer, "; Print speed: {} mm/s", self.config.print_speed)?;
        writeln!(writer)?;
        writeln!(writer, "G21 ; Set units to millimeters")?;
        writeln!(writer, "G90 ; Use absolute coordinates")?;
        writeln!(writer, "M82 ; Use absolute distances for extrusion")?;
        writeln!(writer)?;
        writeln!(writer, "; Heating")?;
        writeln!(writer, "M104 S{} ; Set nozzle temperature", self.config.nozzle_temperature)?;
        writeln!(writer, "M140 S{} ; Set bed temperature", self.config.bed_temperature)?;
        writeln!(writer, "M109 S{} ; Wait for nozzle temperature", self.config.nozzle_temperature)?;
        writeln!(writer, "M190 S{} ; Wait for bed temperature", self.config.bed_temperature)?;
        writeln!(writer)?;
        writeln!(writer, "; Start sequence")?;
        writeln!(writer, "G28 ; Home all axes")?;
        writeln!(writer, "G1 Z15.0 F6000 ; Move platform down 15mm")?;
        writeln!(writer, "G92 E0 ; Reset extruder")?;
        writeln!(writer, "G1 F200 E3 ; Extrude 3mm of filament")?;
        writeln!(writer, "G92 E0 ; Reset extruder")?;
        writeln!(writer)?;

        Ok(())
    }

    fn write_layer(&self, writer: &mut BufWriter<File>, layer: &Layer, layer_index: usize) -> Result<()> {
        writeln!(writer, "; Layer {}", layer_index)?;
        writeln!(writer, "G1 Z{:.3} F{}", layer.z, self.config.print_speed * 60.0)?;

        for contour in &layer.contours {
            if contour.points.is_empty() {
                continue;
            }

            // Move to start of contour (travel move)
            let first = &contour.points[0];
            writeln!(writer, "G1 X{:.3} Y{:.3} F{}", 
                first.x, first.y, self.config.travel_speed * 60.0)?;

            // Extrude along contour
            let mut e = 0.0;
            for point in &contour.points[1..] {
                // Simplified extrusion calculation
                e += 0.1; // This should be calculated based on distance and line width
                writeln!(writer, "G1 X{:.3} Y{:.3} E{:.5} F{}",
                    point.x, point.y, e, self.config.print_speed * 60.0)?;
            }

            // Close contour
            if contour.points.len() > 2 {
                e += 0.1;
                writeln!(writer, "G1 X{:.3} Y{:.3} E{:.5} F{}",
                    first.x, first.y, e, self.config.print_speed * 60.0)?;
            }
        }

        writeln!(writer)?;
        Ok(())
    }

    fn write_footer(&self, writer: &mut BufWriter<File>) -> Result<()> {
        writeln!(writer, "; End sequence")?;
        writeln!(writer, "G92 E0 ; Reset extruder")?;
        writeln!(writer, "G1 E-{} F{} ; Retract filament", 
            self.config.retraction_distance, 
            self.config.retraction_speed * 60.0)?;
        writeln!(writer, "G28 X0 Y0 ; Home X and Y axes")?;
        writeln!(writer, "M104 S0 ; Turn off nozzle heater")?;
        writeln!(writer, "M140 S0 ; Turn off bed heater")?;
        writeln!(writer, "M84 ; Disable motors")?;
        writeln!(writer)?;
        writeln!(writer, "; Print complete")?;

        Ok(())
    }
}
